export const Mentree = [
  {
    id: 58,
    name: "薪酬管理",
    url: "",
    perms: "",
    type: 0,
    icon: "el-icon-document",
    delFlag: 0,
    level: null,
    children: [
      {
        id: 65,
        name: "考勤组管理",
        url: "/sys/signinrules",
        perms: "",
        type: 1,
        icon: "el-icon-time",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 58,
        parentName: null,
        orderNum: 0,
      },
      {
        id: 67,
        name: "出勤天数",
        url: "/sys/attendance",
        perms: "",
        type: 1,
        icon: "el-icon-date",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 58,
        parentName: null,
        orderNum: 0,
      },
      {
        id: 74,
        name: "待更新考勤管理",
        url: "/sys/Signintemporary",
        perms: "",
        type: 1,
        icon: "el-icon-refresh",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 58,
        parentName: null,
        orderNum: 0,
      },
      {
        id: 76,
        name: "孕婴管理",
        url: "/Sys/Babymom",
        perms: "",
        type: 1,
        icon: "el-icon-info",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 58,
        parentName: null,
        orderNum: 0,
      },
      // {
      //   id: 79,
      //   name: "工资表",
      //   url: "/sys/payroll",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-tickets",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 82,
      //   name: "批量提交",
      //   url: "/sys/wageSubmit",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-edit",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 83,
      //   name: "工资分析",
      //   url: "/sys/wageSum",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-picture-outline",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 85,
      //   name: "工资纠正",
      //   url: "/sys/salaryRectify",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-success",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 86,
      //   name: "各考勤组人数",
      //   url: "/Sys/Signinrulesnum",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-edit-outline",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 91,
      //   name: "培训课程管理",
      //   url: "/Sys/CultivateClass",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-news",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 92,
      //   name: "孕婴汇总",
      //   url: "/Sys/BabymonInfo",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-share",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 93,
      //   name: "考勤纠正",
      //   url: "/Sys/SignRectify",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-edit-outline",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 95,
      //   name: "奶粉统计",
      //   url: "/Sys/milkStats",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-edit-outline",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 0,
      // },
      // {
      //   id: 61,
      //   name: "薪酬档案",
      //   url: "/sys/stations",
      //   perms: "",
      //   type: 1,
      //   icon: "el-icon-s-custom",
      //   delFlag: 0,
      //   level: null,
      //   children: [],
      //   parentId: 58,
      //   parentName: null,
      //   orderNum: 1,
      // },
    ],
    parentId: 0,
    parentName: null,
    orderNum: 0,
  },
  {
    id: 1,
    name: "系统管理",
    url: null,
    perms: null,
    type: 0,
    icon: "el-icon-setting",
    delFlag: 0,
    level: null,
    children: [
      {
        id: 2,
        name: "用户管理",
        url: "/sys/user",
        perms: null,
        type: 1,
        icon: "el-icon-service",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 1,
        parentName: null,
        orderNum: 1,
      },
      {
        id: 12,
        name: "角色管理",
        url: "/sys/role",
        perms: null,
        type: 1,
        icon: "el-icon-view",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 1,
        parentName: null,
        orderNum: 4,
      },
      {
        id: 17,
        name: "菜单管理",
        url: "/sys/menu",
        perms: null,
        type: 1,
        icon: "el-icon-menu",
        delFlag: 0,
        level: null,
        children: [],
        parentId: 1,
        parentName: null,
        orderNum: 5,
      },
    ],
    parentId: 0,
    parentName: null,
    orderNum: 10,
  },
];
